### PR TITLE
Fix hx-vals/hx-vars encoding along json-enc

### LINKED ISSUE #56: json-enc incorrectly encodes hx-vals in v2.0.1
I've tried upgrading from 1.9.12 to 2.0.1 and it breaks my app.

## Steps

1) `index.html`:
   ```html
   <!DOCTYPE html>
   <html>
      <head>
         <script src="https://unpkg.com/htmx.org@2.0.1"></script>
         <!-- <script src="https://unpkg.com/htmx.org@1.9.12/dist/htmx.js"></script> -->
         <script src="https://unpkg.com/htmx-ext-json-enc@2.0.0/json-enc.js"></script>
      </head>
      <body>
         <form hx-ext="json-enc" hx-post="/foo" hx-vals="js:{&quot;obj&quot;: {&quot;x&quot;: 123}, &quot;number&quot;: 5000}">
            <button type="submit">Submit</button>
         </form>
      </body>
   </html>
   ```

2) `python3 -m http.server`:

   ```
   ᐅ python3 -m http.server
   Serving HTTP on :: port 8000 (http://[::]:8000/) ...
   ::ffff:127.0.0.1 - - [17/Jul/2024 13:23:13] "GET / HTTP/1.1" 200 -
   ```
3) Browse to http://localhost:8000.
4) Click `Submit` and inspect the corresponding POST request payload in developer tools.

## Expected

`{"obj":{"x":123},"number":5000}`

## Actual

All values are strings now: `{"obj":"{\"x\":123}","number":"5000"}`.

### PR DESCRIPTION
**Pull request by Telroshan**
Fixes #56 

- Current behavior can be observed on [this JSFiddle](https://jsfiddle.net/yzfaj6u0/), notice the incorrect payload
image

- Behavior with this PR's fix can be observed on [this JSFiddle](https://jsfiddle.net/yzfaj6u0/1/), notice the now correct payload
image

### CODE REVIEW

File: src/json-enc/json-enc.js [hunk 1]
```diff
@@ -1,12 +1,32 @@
...
+        evt.detail.headers['Content-Type'] = 'application/json'
+      }
+    },
+
+    encodeParameters: function(xhr, parameters, elt) {
+      xhr.overrideMimeType('text/json')
+
+      const vals = api.getExpressionVars(elt)
+      const object = {}
+      parameters.forEach(function(value, key) {
```
Comment (sameer-dudeja) [inline src/json-enc/json-enc.js:19]: This loop could be smaller using a for... of loop imo. Depends on preferences using DRY principles.

File: src/json-enc/json-enc.js [hunk 2]
```diff
@@ -1,12 +1,32 @@
...
+        // FormData encodes values as strings, restore hx-vals/hx-vars with their initial types
+        if (Object.hasOwn(vals, key)) {
+          object[key] = vals[key]
+        } else {
```
Comment (sameer-dudeja) [inline src/json-enc/json-enc.js:23]: A ternary operator could also be implemented here, again about preference tho.

**Review by sameer-dudeja — APPROVED** [review]
Overall Looks Great.
